kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  namespace: expense
  labels:
    project: expense
    environment: dev
    module: frontend
    tier: web
spec:
  replicas: 1
  selector:
    matchLabels:
      project: expense
      environment: dev
      module: frontend
      tier: web
  template:
    metadata:
      labels:
        project: expense
        environment: dev
        module: frontend
        tier: web
    spec:
      containers:
      - name: frontend
        image: mahalakshmi2997/frontend:v1
        #imagePullPolicy: Always

---

kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    project: expense
    environment: dev
    module: frontend      
    tier: web
  ports:
  - name: frontend
    protocol: TCP
    port: 80
    targetPort: 80

# kind: Service
# apiVersion: v1
# metadata:
#   name: frontend
#   namespace: expense
# spec:
#   type: LoadBalancer
#   selector:
#     app: frontend
#     tier: web
#     project: expense
#   ports:
#   - name: frontend-port
#     protocol: TCP
#     port: 80 # service port
#     targetPort: 80 # container port


