# ------ ststefulset will have headless service and pvc in mandate------------
##headless service##
kind: Service
apiVersion: v1
metadata:
  name: mysql-headless
  namespace: expense
spec:
  clusterIP: None
  selector:
    project: expense
    environment: dev
    tier: db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306

---

# normal service##

kind: Service
apiVersion: v1
metadata:
  name: mysql-svc
  namespace: expense
spec:
  selector:
    project: expense
    environment: dev
    tier: db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    matchLabels:
      project: expense
      environment: dev
      tier: db # has to match .spec.template.metadata.labels
  serviceName: "mysql-headless"
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        project: expense
        environment: dev
        tier: db
         # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mysql
        image: sirishasai2105/mysql:v1
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  # FOR STATEFULSET PVC IS MANDATORY .. IT IS MENTIONED HERE
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "expense-ebs"
      resources:
        requests:
          storage: 1Gi


